export type Kind = 'speech' | 'debate' | 'interview'
export type Speaker = {id: string; name: string; role: 'unspecified' | 'speaker' | 'moderator' | 'interviewer' | 'guest'}
export type Segment = {id?: string; start_ms: number; end_ms: number; text: string; speaker_id: string | null; reviewed: boolean; original_text?: string}
export type Recording = {id: string; title: string; kind: Kind; speaker_count: number; filename: string; duration_ms: number; status: string; error: string | null; revision: number; speakers: Speaker[]; content_date: string | null; scope: string}
export type Transcript = {revision: number; segments: Segment[]}
export type Snapshot = Recording & {segments: Segment[]}
export type ClaimCategory = 'fact' | 'opinion' | 'prediction' | 'question_premise' | 'unverifiable'
export type ClaimStatus = 'proposed' | 'accepted' | 'discarded' | 'edited' | 'stale'
export type ClaimLink = {segment_id:string;start_ms:number;end_ms:number;speaker_id:string|null;speaker_name:string|null;position:number}
export type Claim = {id:string;status:ClaimStatus;revision:number;normalized_text:string;original_quote:string;category:ClaimCategory;verifiable:boolean;start_ms:number;end_ms:number;ambiguity_notes:string[];missing_context:string[];segments:ClaimLink[]}
export type ClaimRunStatus = 'queued' | 'running' | 'completed' | 'failed' | 'stale' | 'cancelled'
export type ClaimRun = {id:string;recording_id:string;recording_revision:number;kind:string;status:ClaimRunStatus;provider:string;model:string|null;prompt_version:string;usage:Record<string,unknown>|null;error:string|null;unreviewed_segment_count:number;created_at:string;completed_at:string|null;claims?:Claim[]}
export const kinds: Record<Kind, string> = {speech: 'Discurso', debate: 'Debate', interview: 'Entrevista'}
export const statuses: Record<string, string> = {received:'Recibida', queued:'En cola', transcribing:'Transcribiendo', ready_for_review:'Lista para revisión', cancelled:'Cancelada', failed:'Error de procesamiento'}
